// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserDb;

#nullable disable

namespace UserDb.Migrations
{
    [DbContext(typeof(FunctionAppDbContext))]
    [Migration("20230910230613_create_sp_dbo_get_users")]
    partial class create_sp_dbo_get_users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserDb.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NotificationFlag")
                        .HasColumnType("bit");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedTime = new DateTime(2023, 9, 11, 1, 6, 13, 286, DateTimeKind.Local).AddTicks(3966),
                            DataValue = "Some value",
                            Email = "user1@abc.com",
                            NotificationFlag = false,
                            RecordId = 1,
                            UpdatedTime = new DateTime(2023, 9, 11, 1, 6, 13, 286, DateTimeKind.Local).AddTicks(4014),
                            UserName = "User 1"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedTime = new DateTime(2023, 9, 11, 1, 6, 13, 286, DateTimeKind.Local).AddTicks(4018),
                            DataValue = "Some value",
                            Email = "user2@abc.com",
                            NotificationFlag = false,
                            RecordId = 2,
                            UpdatedTime = new DateTime(2023, 9, 11, 1, 6, 13, 286, DateTimeKind.Local).AddTicks(4020),
                            UserName = "User 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
